FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04

ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    python3-dev \
    pkg-config \
    ffmpeg \
    libavdevice-dev \
    libavfilter-dev \
    libavformat-dev \
    libavcodec-dev \
    libswresample-dev \
    libswscale-dev \
    libavutil-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN pip3 install --upgrade pip
RUN pip3 install  torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu121
COPY requirements.txt .
RUN pip3 install  -r requirements.txt 
COPY main.py .
EXPOSE 8001
CMD ["python3", "-m","uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
